# Obelisk config for hello-world activity only

api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

[log.stdout]
enabled = true

[[activity_wasm]]
name = "hello_world"
location.path = "activity/hello-world/hello-world-ts/dist/hello-world-ts.wasm"
forward_stdout = "stderr"
forward_stderr = "stderr"
